-- Sirat Database Migration
-- New tables + column changes

CREATE TABLE IF NOT EXISTS wishlist (
  id VARCHAR(255) PRIMARY KEY,
  userId VARCHAR(255) NOT NULL,
  productId VARCHAR(255) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS passwordresettoken (
  id VARCHAR(255) PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  otp VARCHAR(6) NOT NULL,
  expiresAt DATETIME NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cart (
  id VARCHAR(255) PRIMARY KEY,
  userId VARCHAR(255) NOT NULL UNIQUE,
  items TEXT,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

ALTER TABLE `order` ADD COLUMN IF NOT EXISTS discountAmount DOUBLE DEFAULT 0;
ALTER TABLE `order` ADD COLUMN IF NOT EXISTS couponCode VARCHAR(255);
