-- Sirat Database Migration
-- New tables + column changes

CREATE TABLE IF NOT EXISTS wishlist (
  id VARCHAR(255) PRIMARY KEY,
  userId VARCHAR(255) NOT NULL,
  productId VARCHAR(255) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS passwordresettoken (
  id VARCHAR(255) PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  otp VARCHAR(6) NOT NULL,
  expiresAt DATETIME NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cart (
  id VARCHAR(255) PRIMARY KEY,
  userId VARCHAR(255) NOT NULL UNIQUE,
  items TEXT,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

ALTER TABLE `order` ADD COLUMN IF NOT EXISTS discountAmount DOUBLE DEFAULT 0;
ALTER TABLE `order` ADD COLUMN IF NOT EXISTS couponCode VARCHAR(255);

CREATE TABLE IF NOT EXISTS teammember (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  bio TEXT,
  avatar VARCHAR(255),
  twitter VARCHAR(255) DEFAULT '',
  linkedin VARCHAR(255) DEFAULT '',
  github VARCHAR(255) DEFAULT '',
  instagram VARCHAR(255) DEFAULT '',
  facebook VARCHAR(255) DEFAULT '',
  website VARCHAR(255) DEFAULT '',
  `order` INT DEFAULT 0 NOT NULL,
  isActive BOOLEAN DEFAULT TRUE NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
